const decentraland = {
  name: "Decentraland",
  description:
    "Decentraland is an Ethereum blockchain-powered virtual world, developed and owned by its users, who can create, experience, and monetize content and applications. Join a growing community of virtual world inhabitants who are building the world's largest alternate reality economy on the blockchain. In this store, you can buy and sell land assets in MANA, DCL's native currency.",
  banner_image_url: "https://storage.opensea.io/static/banners/dclwearables-banner.png",
  large_image_url:
    "https://lh3.googleusercontent.com/ZIOoCXJlOBaaY79prMWkQQ05odBTbkpg8A30EEO919lQbhCw9fv0kMf3QK1EMmz0cdS4-KWAUVWPtjz3ca_F2pkyD6v7AJre4tLjwA=s300",
  assets: [
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "12600 m2 lot",
      description: null,
      traits: [
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/5lb5aBDyQZ_tdkjWCYP4COMGdwZSZki8dlewl3jg5HqOeZQLLjbYHcIfrerIY6YtnbhQmoA94nisQDWHFy99PhAe2R0qugif6BD4xw",
      name: "SUNSET STRIP ON SUNSET BOULEVARD",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 90,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/PW67IWXv2v396ETjSGsV-EvvAzLN1vbiZ3Qv4xBT8TUmGbuLv4tMy4SektHIJXDVf4goJQxasoAAAYAnDd1_CvqJ_24cxMgieDyxnA",
      name: "The Moon Room",
      description: null,
      traits: [
        {
          trait_type: "Distance to District",
          value: 2,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 50,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "landmarket@pm.me",
      description: "landmarket@pm.me",
      traits: [
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/b_wUdcMY8nPCA3EEvn6Zvm9QXd3obaiQTvdPkdOGGKhOEIXL62YFh5GW2z6DbHcXRgmrbNc1ToFfwGFNFbXen7ItTO5Ds0we6EeZ",
      name: "PhiAMT Park, Lemursiv, and Pixels for Madagascar",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 64,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Ie72TFcTuPoeBy3wiP3EMMXS5fqnsg1511Qd-XbG8N0vTo652ZR_5KDOi6mP7Rox7cYJXQ5dcBTNaBfPM4ImBA6kXmsaQIh992T-ZQ",
      name: "Republic Realm",
      description: null,
      traits: [
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
        {
          trait_type: "Size",
          value: 259,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/aaPC8XgvSROlr3JX0G5yHlqhc9HLcBePkp4SyGodDwPr_YXTsb2UDRVxi3GsNXn1oYJT3zyfiaX3v7FKKpq9NM_g4ohNN72ircd34w",
      name: "PENGUIN CLUB",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 20,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 3,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Plaza",
          value: 2,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/anSrTvU2DnBbh2O9fL-yNI6WFYkiS3WtT7BJvBDLKvI2NQGPpauxh030s-V9h1FwREusTMFZsMviaFv7sb0v9kHxJSkiDKuNU94Q5A",
      name: "From Nessie To You",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 44,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/fxk2PwB99_-_1w7ZLSDEKZSKt8eIdbWCwgrhzuG2kkdhG-Vk87StBmL6CH696QQM-wU2HcXZSbafVD3olCDaeKFV1jXZlKcjBKSMsg",
      name: "X1",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 2,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 54,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 4,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/UGnvldPiVxNgIhJBS62C4ItmabICbg-1SuIw7IWnUN3q0y8kKkDPgv44NbkzVXx6Bh_yq-xiCTng3yC6vY0HaemYkivNHtGgB9v8Ng",
      name: "Virtual Eternal Estates V2.1",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 56,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/UrSWERTH3eZpaXFF0Y6SyUyc5EA0Ys-_FutyyPT0rbrfEqXxj2MRYvEsepVJvgvjUIqD6BecCgZpHZngIisaZcsUI0RITmeCQHWC",
      name: "Premium Estate",
      description: null,
      traits: [
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
        {
          trait_type: "Size",
          value: 144,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Gw0QKpPQGgSrun72tD7wYlnR0eVruESAIGqYvKrC34tApRTaOF3pvPFBJmuVZXEdTELDJLuY6HrRUrczS6RxTXl4th5Gc4X5tr3NiLQ",
      name: "Main Road Asset",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 12,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "WHALE Estate |Send offers to dclbloggerx@gmail.com",
      description: "11,520 m2 (124,000 sq ft) 100m+ Build height!",
      traits: [
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/qX1JDxyP2AUTsNOfxaq3hrKV7E7tlwFdcz3gLc9Rpe2I9ScHbrH54yAtsrIyho8C40C8gl5A5AKHQiIDwf7waqT9rct1FzA0651X",
      name: "under constructions",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 6,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "Caesar's Palace",
      description: "🔥 HOT 🔥  one of the BEST position of the Map. Near Vegas, University. 4x road touch",
      traits: [
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/vyuTmpiJnZhbMFWQ1wgbDmj8iR9ENR-PVPGrfFdmCWQDAo-kizK3PLLsjmhS-rNboSxRa8ITNeMFbePA_tGcggyCLKCvLEKPpBuZMA",
      name: "Fashion Street Estate",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 116,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/dOG9pGEd8c6ETnh-CcokUQw0RY5ZofHW6-hQXyEFXwJIz31p6oqmCkN-yOY_6Vi12GC2G1X2I2EqU0Dn6xRvTbC9WIqE_zNaaU6_IA",
      name: "UC Foton",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 6,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 24,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/OQGEmZLj5CAoHoFd_5_STDNpC3XseAYRsCb3ky0g3ptNNJekKwK02IvyrchrlWKE-3Js1XsuqLdJs15HvGL7q1mCeGx1cJ9Y2DM90A",
      name: "under constructions",
      description: null,
      traits: [
        {
          trait_type: "Distance to District",
          value: 2,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 9,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "Sol / LayerX Estate",
      description: "Premium estate near main road, Genesis Plaza and Dragon City",
      traits: [
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/JCsTl0GIUbcwmJm0sKJdonKuwk2WccZ7p3mzXgEWz541taLX8-daFqmSC5nuAM717qV1XxWHqZHGTKBIJoLxNu3li96bGb5tlww2fkA",
      name: "888",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 40,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/JYcC4PkV_kL2sXDToapKfOVZdU2_IpoJdG14JebWI5WlccbQllrJGxgMBDjFCgACfNRIqB_6agcFMAID5GYTSyzRSKII_P0EbQR0Gw",
      name: "Imbrex Commons",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 10,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/wuAVFYlmnIYucDG8pP3XNn5cDziR9pbxYjMg5jtcuwhvTALHK-e2_r87qsMpbAnEgMY7uBOzZAs_NQGyP-D1A-BVRfGtrlVdS2JL1w",
      name: "The Chunk",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 29,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/RCNCaA8vHJ0o-v3J8ox1s-vTwQCQhtydHk6QZD-afoizDGPIOpm2MnZVVDgvWfPmkaoc8Ep1boAZ2d_RfI6j-SckZserLTRD7hwu",
      name: "Point",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 12,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Tv9Nkr8Ip5I80WzIo2u1utJdn2D1eS1cQ7stiYKH0lb6QjKuQEkjmkBnu1ZCdBBo9f_q4eMtNSY5y83INHkpg5G2W0XfueLYNCre",
      name: "Not Fungible Headquarters",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 20,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 2,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/3J-kobipiK--v_sLiyBNmU_6MQzlIJ4X7QkstHXGiondWkpDuZEbtzvI-fhTe1eWcQobXSXSkWwbKCcYUSeOen_hT56KI5YuX1Yr",
      name: "📘📘📘📘📘Stratis Breeze Wallet📘📘📘📘📘",
      description: null,
      traits: [
        {
          trait_type: "Distance to Plaza",
          value: 7,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 5,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 21,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 4,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/kgMb6EfgHBNt-W5s4TSwyQQHB2kF4UTu9kjVRm0lf0yJ0okV1h6rFhS119Jd_NU0XjufspcrkdmKJ6GZga_PpNDkG0VmIeWlwdcD",
      name: "Hope",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 2,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 10,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/BKZPoq7U4cuWsudeao-1QhFtO4HVshtgikUa99faOh40bvZWRDb_6X77XuqahTm5LxGzqCfoka6KtpvCT7WyISB6GLven82X_eLU7S4",
      name: "UC Foton",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 6,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/YaR9lcmrGFQhlwWoqjqRsqyMfyZP-LqUspnffCjQqpWi5KsSbmHtd28qg-1LDsIXYj05NcVlex5dynFpa6EA-TMaiKJtmgS1-VtPzZc",
      name: "Perfect Estate at the crossroad of  Mainroad 50;50",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 12,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/lkUophK7m0ggQT4v8b607RL6eg92gNeDPw6W1CA6E4Rf4oX1yb8blmEFX29sU8B_BEL3mADyllf5oVxdNuRqwNysuNZw2Z73gohysg",
      name: "theroad",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 78,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Plaza",
          value: 5,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "wdhwer@qq.com",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/JPqeIP3txUrDIIKLvRTy5ikf4Ar3XZ3pPzuBMAyr7BO9urdsaAHrlVUj-9jkUP5MaO5Bo2ZBFIKOUo2w6dFcfJepsnGUAF9HQlCZvg",
      name: "Best positioned estate in Aetherian",
      description: null,
      traits: [
        {
          trait_type: "Distance to District",
          value: 2,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 14,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/DpdEd49VBEgFeTuagib1Qu4a9lrH2obBrGRThq6D-GsqWJU5K8NQbsA68CyIwO3e8ncJAf0jwQHoXq9tuQcgrr9xh8sInqADmQGVxg",
      name: "Sparta",
      description: null,
      traits: [
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
        {
          trait_type: "Size",
          value: 27,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 1,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "Closetheria",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Ov1qpz2-4vjK2_DqoSk0riNUSw-yPlFxsI01KO4KQjXSJd81Iy2j_xEHSKIOkLJ_ShZq9N_S2RAKX1I4InQXLW0Cp_nxTrZslFR3gqo",
      name: "MASSIVE SKYSCRAPER 80M HEIGHT. HUGE TRAFFIC",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 18,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Plaza",
          value: 5,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "offers at dclbloggerx@gmail.com | dclblogger.com",
      description: "dclblogger.com",
      traits: [
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/UN4X1TYl6-wbHpf0FUvUb_aXjGkeXohZYyubOc7kD4WJWXCzA7-7R3N-4kxlrQsPECH0brD81L22gciQJMdgZrHcg1YjTNA2CLNCow",
      name: "Fashion Interconnect",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 1,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 53,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/N5iyrZgx3FPOoUsTW4CffwkcVrsaBBb4dFYhzed_8Xj9IO8LIgChse8ztiIUa9BPqZkrna_o9dalRHEiBtMDLv56O9K3xXjsAfQX",
      name: "High Traffic Genesis Estate",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 29,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 9,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/WR7zTgMuoOGEey0nCSjTewIpsgM_NDR_wuGSCcXN_dEY_2BZ5w18DD6mQj-eG_LwObN6PbbBgmO7d0l63wJOWBFUPyH-j_LgzsLjag",
      name: "DRAGON PRIME",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 9,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/SSKK4XI3QKoLl3vibkMjOCnt_be7P3KlZBPHGIOxiYuTGv0NoeyozUAzRNYiCiG2ySXjdeK2q75hYl0ut1KPJvPHDUQ4z05IYtE8G20",
      name: "😎Xeonbit Mansion 😎",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 4,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "Overlooking everything",
      description:
        "What a great location ! Overlooking The battleground and DragonKingdom districts easy with 93 meters building heights its a prime estate !",
      traits: [
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Qbpg8Qq_2Nzx3hLsXvAYbaJiIbx5bRlLBPSfZ4IWujM5QhARtUm6WWtul9ch5XScxE3-GICrXCzzig26I58rMj17yRdUcAP_C7ncfqk",
      name: "Fool Moon Rising",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 4,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/2KvjTg-eJIv4YGcwyzfL_CYz7EmyekSXiLkTteVkPcqod8Bd0dPgoWWgcmLlYxrhUSs84Yj7CHiiD71zPTifSCsv_BeRdefMDkCS2GU",
      name: "Money Tower",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 16,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/4d_tnKcZ2mqtLQLpX62T3BmogCO6YXZq0O_XoMs6jtN6IZccDc7wUT_Zi0dszAlvZDEDFRH9P4CTkevXwhen98C6-qBJaSjTRtL6UV8",
      name: "thx",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 20,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 2,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/FORn-qGhi3WKATvrbrGcqU6LN51Q91ad0npW00kS7L722O1JBQ1dB91UEsNBqxxB-7q2z3W_7LGHYlr5Dx6bPvaP8OvFPG-5W5zg_w",
      name: "Estate Gateway",
      description: null,
      traits: [
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Plaza",
          value: 2,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 6,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "S",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/OoR_Gfp3deq6jJ7aLLRgzP2AUaf0LRtDOZ2n8IOe9suubXcEGbXOXhVldfShj7iEaLQYDytrmJKgUyNC5YEUKDHrZGD88uoFNy9_YT8",
      name: "ZionVI",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 26,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 1,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/Jd1fbhXjmZIW-jFwMINw__mzxd-oi32wGLWrhX1wcicYrEPUyCdnAbMVVPSYdh286iiv47mjWQbRGD2usLXOHqiJTzLfOxfiEgB2Ig",
      name: "Game developers studio A",
      description: "unique location for development, large road access, height build, facing Dragon city",
      traits: [
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
        {
          trait_type: "Size",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/PoPtaxONcqgkBgBiVpl3KNQANmy3HC7jwb1KyXquJBu_6VAdeAvQKUmhITTUWJzhGfx3MzOoVGkzBsnRVIOCw99S5Wc1-DEslGkK",
      name: "Momus Park - Exhibit A",
      description: null,
      traits: [
        {
          trait_type: "Distance to District",
          value: 5,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 20,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 0,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/QxIE5yEVFF1IaVArMsIvpKJo-f0zb3I30TFssGgbU8fMp-cMTgebffFEm8biKtVxkPlFvZ4rSe6IzzYRlSWVXRUxpZTrEFjZ_Gd-ztw",
      name: "Pranksy Palace",
      description: null,
      traits: [
        {
          trait_type: "Size",
          value: 36,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 6,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 5,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
    {
      tokenURI:
        "https://lh3.googleusercontent.com/5DyuyflrrN39jDmKk7oVGI5h0Rx432qOeqPAYIqwbtZ4_pjmbnFnzIHzxY4Iq0JQY0VCS8730_OGoxu0up2qu0ecw6f8AmYoBe18qKA",
      name: "X2",
      description: null,
      traits: [
        {
          trait_type: "Distance to Plaza",
          value: 6,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Size",
          value: 28,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to Road",
          value: 4,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Distance to District",
          value: 9,
          display_type: "number",
          max_value: null,
          trait_count: 0,
          order: null,
        },
        {
          trait_type: "Type",
          value: "Estate",
          display_type: null,
          max_value: null,
          trait_count: 4602,
          order: null,
        },
      ],
    },
  ],
};
module.exports = decentraland;